### ISSUE TITLE
Video is not showing

### ISSUE THREAD

**Issue by akkalbhor** [AbedElazizShe/LightCompressor#11]
I have recorded a video of 10 secs and then I try to compress it. It is showing a black screen with audio only.

**Comment by AbedElazizShe** [comment]
Thank you for posting this issue. Could you please share one of these videos so I can debug it on my side? You can upload it to Google drive and share the link. Please let me know what device you're using and which Android version, so I might be able to reproduce the issue.

**Comment by akkalbhor** [comment]
HI @AbedElazizShe 

I am using one plus 6 on andorid 10. 
for recording video using camera, I have used this https://github.com/MasayukiSuda/CameraRecorder-android library.

Input - https://drive.google.com/file/d/1LNtE0NLfSbopgckn48IughZ7HkCTt5__/view?usp=sharing
Output - https://drive.google.com/file/d/15ZYfLQPPdjHPusgPS0Vq317pjOt7sT_Q/view?usp=sharing

**Comment by AbedElazizShe** [comment]
Please give me access to the videos. You can choose permissions to `anyone with link` or add my email `elaziz.shehadeh@gmail.com`

**Comment by akkalbhor** [comment]
Yes, I have added your email. have you checked?

**Comment by AbedElazizShe** [comment]
Hello, 

Thank you for sharing the videos with me. I tried you input and i could compress it without any problem. Size after compression is 1.8 MB and took 2 seconds at Medium quality.

Can you try to compress on a different device or an emulator ? So maybe I can narrow down the causes of it on your side.

Thank you

**Comment by akkalbhor** [comment]
Hi 

Thank you for your time,

As of now, I have checked it on

1. One plus 6 version 10.
2. One plus 3T version 9.
3. Moto G3 version 6.0.1
4 Emulator Pixel XL version 8.1 
5. Samsung M21 version 10.

in all facing the same issue.

**Comment by akkalbhor** [comment]
hi did you checked?

**Comment by AbedElazizShe** [comment]
Hello, I have checked on simulators and real devices with the video you shared with me. It is working fine. If you can debug and provide me with some more details, I will fix it. However, I will investigate more during the weekend. Thank you

**Comment by akkalbhor** [comment]
Hi, I have already mailed you the one APK and STR can you please check that too whenever you get time. 
Thanks.

**Comment by BetoRincon** [comment]
Hello, I'm having the same problem

**Comment by AbedElazizShe** [comment]
Hello,
Thank you for your email, I have replied and looking forward to your response.

As I stated in my email, the video generated from your app (original) is compressed just fine with the library's sample app. The issue is potentially with the way the library is implemented in the app or a crash somewhere that is not handled, I will fix the problem with your help.

Thank you

**Comment by BetoRincon** [comment]
Yep, you are right. I use the project application and work fine 🤔

**Comment by akkalbhor** [comment]
Hi,

Here is the link to my project. Please let me know if you require anything.

https://drive.google.com/file/d/1B93u6QHzmiLcA6AYkqGEvovw1flXlf6Y/view?usp=sharing

Thank you.

**Comment by AbedElazizShe** [comment]
Thank you for your feedback, 

The problem was due to a video generated on your phone with a bitrate less than the min allowed in the library, and you specifically pass `isMinBitrateEnabled` to true. Setting that to false would solve your issue.

I have added a better way to show failure messages to give you an idea of what went wrong.

Please update the library to version 0.6.0 and have a look at the implementation again from [here](https://github.com/AbedElazizShe/LightCompressor#java). You will need to add `String failureMessage` to onFailure and pass and extra parameter true/false to keepOriginalResolution 

Thank you and happy coding :)

**Comment by akkalbhor** [comment]
Hi,

This is not fixed yet. I tried setting isMinBitrateEnabled to false still the same result and the generated bitrate from my mobile is 6894758 which is more than allowed in the library.

**Comment by AbedElazizShe** [comment]
I tried your project and it's working, I forgot to mention that you need to handle destination file better. For example, i am saving in downloads folder. So modified your destFile with 
`  File downloadsPath =
                Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        File desFile = new File(downloadsPath, System.currentTimeMillis() + "_" + "myVideoName.mp4");
        if (desFile.exists()) {
            desFile.delete();
            try {
                desFile.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }`
