### ISSUE TITLE
Compression stopped working for many devices starting from version 0.7.6

### ISSUE THREAD

**Issue by Andoctorey** [AbedElazizShe/LightCompressor#55]
I see a lot of logs in Crashlytics mostly on Samsung devices:
1. Compression starts for big video file
2. Library return on Success in 100ms with empty file

I reproduce in office on Galaxy S8 SM-G950FD, Android 9 with this video: https://drive.google.com/file/d/17BBYMml1Lvn1OJAMrAYI6br_Ef0H22fc/view?usp=sharing
and params: VideoQuality.HIGH, isMinBitRateEnabled = true, keepOriginalResolution = true

Everything works OK in version 0.7.5

**Comment by AbedElazizShe** [comment]
@Andoctorey thank you for opening the issue and I appriciate the details and the sample video. I will investigate the issue on Galaxy S8 as I could compress the video on Pixel 2. Original size 377.1 MB compressed to 115.2 MB on high quality in 1:21 time. Could you please try the sample apk in README on the same device and let me know if you have the same issue.

If you can post what kind of crashes reported in crashlytics, it would be a great help too.

Thank you. Will inform you if I could find the issue here.

**Comment by AbedElazizShe** [comment]
Thank you @Andoctorey for your input, the issue is fixed in the last release 0.7.9. Please let me know if you have any issues.

**Comment by Andoctorey** [comment]
It works in 0.7.9! Thank you!
